### ISSUE TITLE
Proxy Startup fails

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpProxyR66#32]
Hello Frédéric,

I have some trouble starting the proxy server... my command is:

``java -server -Xms256m -Xmx4096m  -cp  /opt/R66/lib/WaarpProxyR66-3.0.2.jar:/opt/R66/lib/*   -Dlogback.configurationFile=/opt/R66/conf/logback.xml   org.waarp.openr66.proxy.R66Proxy /opt/R66/conf/config-proxy.xml``

<pre><code>
11/02/2016/16:58:56.970 DEBUG [org.waarp.common.logging.WaarpLoggerFactory] [main] org.waarp.common.logging.WaarpLoggerFactory.<clinit>(WaarpLoggerFactory.java:45) : Using Logback (SLF4J) as the default logging framework
11/02/2016/16:58:56.990 DEBUG [io.netty.util.internal.logging.InternalLoggerFactory] [main] Using SLF4J as the default logging framework
11/02/2016/16:58:57.081 DEBUG [io.netty.util.ResourceLeakDetector] [main] -Dio.netty.leakDetection.level: simple
11/02/2016/16:58:57.086 DEBUG [io.netty.util.ResourceLeakDetector] [main] -Dio.netty.leakDetection.maxRecords: 4
11/02/2016/16:58:57.117 DEBUG [io.netty.util.internal.PlatformDependent0] [main] java.nio.Buffer.address: available
11/02/2016/16:58:57.119 DEBUG [io.netty.util.internal.PlatformDependent0] [main] sun.misc.Unsafe.theUnsafe: available
11/02/2016/16:58:57.122 DEBUG [io.netty.util.internal.PlatformDependent0] [main] sun.misc.Unsafe.copyMemory: available
11/02/2016/16:58:57.123 DEBUG [io.netty.util.internal.PlatformDependent0] [main] java.nio.Bits.unaligned: true
11/02/2016/16:58:57.126 DEBUG [io.netty.util.internal.PlatformDependent] [main] Java version: 7
11/02/2016/16:58:57.127 DEBUG [io.netty.util.internal.PlatformDependent] [main] -Dio.netty.noUnsafe: false
11/02/2016/16:58:57.128 DEBUG [io.netty.util.internal.PlatformDependent] [main] sun.misc.Unsafe: available
11/02/2016/16:58:57.130 DEBUG [io.netty.util.internal.PlatformDependent] [main] -Dio.netty.noJavassist: false
11/02/2016/16:58:57.413 DEBUG [io.netty.util.internal.PlatformDependent] [main] Javassist: available
11/02/2016/16:58:57.414 DEBUG [io.netty.util.internal.PlatformDependent] [main] -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
11/02/2016/16:58:57.415 DEBUG [io.netty.util.internal.PlatformDependent] [main] -Dio.netty.bitMode: 64 (sun.arch.data.model)
11/02/2016/16:58:57.416 DEBUG [io.netty.util.internal.PlatformDependent] [main] -Dio.netty.noPreferDirect: false
11/02/2016/16:58:57.537 INFO [org.waarp.openr66.protocol.configuration.Configuration] [main] org.waarp.openr66.protocol.configuration.Configuration.computeNbThreads(Configuration.java:1093) : Change default number of threads to 9
11/02/2016/16:58:57.897 INFO [org.waarp.openr66.proxy.configuration.FileBasedConfiguration] [main] org.waarp.openr66.proxy.configuration.FileBasedConfiguration.loadDatabase(FileBasedConfiguration.java:999) : Unable to find DBDriver in Config file
11/02/2016/16:58:58.003 DEBUG [org.waarp.common.crypto.ssl.WaarpSslContextFactory] [main] org.waarp.common.crypto.ssl.WaarpSslContextFactory.initSslContextFactory(WaarpSslContextFactory.java:137) : No TrustManager
11/02/2016/16:58:58.472 DEBUG [org.waarp.snmp.SnmpConfiguration] [main] org.waarp.snmp.SnmpConfiguration.loadTarget(SnmpConfiguration.java:578) : Addr: class org.snmp4j.smi.UdpAddress 127.0.0.1/162
11/02/2016/16:58:58.475 DEBUG [org.waarp.snmp.SnmpConfiguration] [main] org.waarp.snmp.SnmpConfiguration.loadTarget(SnmpConfiguration.java:578) : Addr: class org.snmp4j.smi.UdpAddress 127.0.0.1/162
11/02/2016/16:58:58.477 INFO [org.waarp.openr66.proxy.configuration.FileBasedConfiguration] [main] org.waarp.openr66.proxy.configuration.FileBasedConfiguration.loadLimit(FileBasedConfiguration.java:667) : Global Limit: 0
11/02/2016/16:58:58.478 INFO [org.waarp.openr66.proxy.configuration.FileBasedConfiguration] [main] org.waarp.openr66.proxy.configuration.FileBasedConfiguration.loadLimit(FileBasedConfiguration.java:677) : SessionInterface Limit: 0
11/02/2016/16:58:58.479 INFO [org.waarp.openr66.proxy.configuration.FileBasedConfiguration] [main] org.waarp.openr66.proxy.configuration.FileBasedConfiguration.loadLimit(FileBasedConfiguration.java:690) : Delay Limit: 10000
11/02/2016/16:58:58.480 INFO [org.waarp.openr66.proxy.configuration.FileBasedConfiguration] [main] org.waarp.openr66.proxy.configuration.FileBasedConfiguration.loadLimit(FileBasedConfiguration.java:705) : Limit of Runner: 10
11/02/2016/16:58:58.533 DEBUG [org.waarp.common.crypto.ssl.WaarpSslContextFactory] [main] org.waarp.common.crypto.ssl.WaarpSslContextFactory.initSslContextFactory(WaarpSslContextFactory.java:133) : Has TrustManager
11/02/2016/16:58:58.535 DEBUG [org.waarp.common.crypto.ssl.WaarpSslContextFactory] [main] org.waarp.common.crypto.ssl.WaarpSslContextFactory.initSslContextFactory(WaarpSslContextFactory.java:159) : Has TrustManager
11/02/2016/16:58:58.553 DEBUG [io.netty.channel.MultithreadEventLoopGroup] [main] -Dio.netty.eventLoopThreads: 8
11/02/2016/16:58:58.606 DEBUG [io.netty.channel.nio.NioEventLoop] [main] -Dio.netty.noKeySetOptimization: false
11/02/2016/16:58:58.607 DEBUG [io.netty.channel.nio.NioEventLoop] [main] -Dio.netty.selectorAutoRebuildThreshold: 512
11/02/2016/16:58:58.687 DEBUG [io.netty.channel.DefaultChannelId] [main] -Dio.netty.processId: 181 (auto-detected)
11/02/2016/16:58:58.693 DEBUG [io.netty.channel.DefaultChannelId] [main] -Dio.netty.machineId: 02:42:ac:ff:fe:11:00:33 (auto-detected)
11/02/2016/16:58:58.698 DEBUG [io.netty.util.internal.ThreadLocalRandom] [main] -Dio.netty.initialSeedUniquifier: 0xdc42f3e25057f451 (took 39 ms)
11/02/2016/16:58:58.837 DEBUG [io.netty.buffer.PooledByteBufAllocator] [main] -Dio.netty.allocator.numHeapArenas: 8
11/02/2016/16:58:58.838 DEBUG [io.netty.buffer.PooledByteBufAllocator] [main] -Dio.netty.allocator.numDirectArenas: 8
11/02/2016/16:58:58.839 DEBUG [io.netty.buffer.PooledByteBufAllocator] [main] -Dio.netty.allocator.pageSize: 8192
11/02/2016/16:58:58.839 DEBUG [io.netty.buffer.PooledByteBufAllocator] [main] -Dio.netty.allocator.maxOrder: 11
11/02/2016/16:58:58.840 DEBUG [io.netty.buffer.PooledByteBufAllocator] [main] -Dio.netty.allocator.chunkSize: 16777216
11/02/2016/16:58:58.841 DEBUG [io.netty.buffer.PooledByteBufAllocator] [main] -Dio.netty.allocator.tinyCacheSize: 512
11/02/2016/16:58:58.841 DEBUG [io.netty.buffer.PooledByteBufAllocator] [main] -Dio.netty.allocator.smallCacheSize: 256
11/02/2016/16:58:58.842 DEBUG [io.netty.buffer.PooledByteBufAllocator] [main] -Dio.netty.allocator.normalCacheSize: 64
11/02/2016/16:58:58.842 DEBUG [io.netty.buffer.PooledByteBufAllocator] [main] -Dio.netty.allocator.maxCachedBufferCapacity: 32768
11/02/2016/16:58:58.843 DEBUG [io.netty.buffer.PooledByteBufAllocator] [main] -Dio.netty.allocator.cacheTrimInterval: 8192
11/02/2016/16:58:58.869 DEBUG [io.netty.buffer.ByteBufUtil] [main] -Dio.netty.allocator.type: pooled
11/02/2016/16:58:58.870 DEBUG [io.netty.buffer.ByteBufUtil] [main] -Dio.netty.threadLocalDirectBufferSize: 65536
11/02/2016/16:58:58.914 WARN [org.waarp.openr66.protocol.configuration.Configuration] [main] org.waarp.openr66.protocol.configuration.Configuration.pipelineInit(Configuration.java:662) : Server Thread: 2 Client Thread: 4 Runner Thread: 10
11/02/2016/16:58:58.916 INFO [org.waarp.openr66.protocol.configuration.Configuration] [main] org.waarp.openr66.protocol.configuration.Configuration.pipelineInit(Configuration.java:668) : Current launched threads: 7
11/02/2016/16:58:58.925 DEBUG [org.waarp.openr66.proxy.configuration.Configuration] [main] org.waarp.openr66.proxy.configuration.Configuration.r66Startup(Configuration.java:89) : Start R66: 6666:true 6667:true:proxy1R66
11/02/2016/16:58:58.954 DEBUG [io.netty.util.NetUtil] [main] Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%1)
11/02/2016/16:58:58.957 DEBUG [io.netty.util.NetUtil] [main] /proc/sys/net/core/somaxconn: 128
11/02/2016/16:58:58.979 DEBUG [org.waarp.common.cpu.WaarpConstraintLimitHandler] [main] org.waarp.common.cpu.WaarpConstraintLimitHandler.setHandler(WaarpConstraintLimitHandler.java:424) : Activate Throttle bandwidth according to CPU usage
11/02/2016/16:58:59.003 ERROR [org.waarp.openr66.proxy.R66Proxy] [main] org.waarp.openr66.proxy.R66Proxy.initialize(R66Proxy.java:70) : Startup of Proxy is in error
io.netty.channel.ChannelException: address already in use by: [id: 0xf614046c, local:0]
        at io.netty.channel.local.LocalChannelRegistry.register(LocalChannelRegistry.java:46) ~[netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.local.LocalServerChannel.doBind(LocalServerChannel.java:91) ~[netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:538) ~[netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1196) ~[netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeBindNow(ChannelHandlerInvokerUtil.java:108) ~[netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeBind(DefaultChannelHandlerInvoker.java:214) ~[netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:208) ~[netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1003) ~[netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:232) ~[netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:357) ~[netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339) ~[netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356) ~[netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) ~[netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_95]
11/02/2016/16:58:59.012 INFO [org.waarp.openr66.protocol.utils.ChannelUtils] [main] org.waarp.openr66.protocol.utils.ChannelUtils.exit(ChannelUtils.java:371) : Current launched threads before exit: 12
11/02/2016/16:58:59.027 WARN [org.waarp.openr66.protocol.localhandler.LocalTransaction] [main] org.waarp.openr66.protocol.localhandler.LocalTransaction.shutdownLocalChannels(LocalTransaction.java:404) : Will inform LocalChannels of Shutdown: 0
11/02/2016/16:58:59.029 INFO [org.waarp.openr66.protocol.utils.ChannelUtils] [main] org.waarp.openr66.protocol.utils.ChannelUtils.exit(ChannelUtils.java:385) : Unbind server network services
11/02/2016/16:58:59.031 WARN [org.waarp.openr66.protocol.utils.ChannelUtils] [main] org.waarp.openr66.protocol.utils.ChannelUtils.exit(ChannelUtils.java:387) : Exit: Give a delay of 10000 ms
11/02/2016/16:59:09.043 INFO [org.waarp.openr66.protocol.utils.ChannelUtils] [main] org.waarp.openr66.protocol.utils.ChannelUtils.exit(ChannelUtils.java:399) : Exit Shutdown Http
11/02/2016/16:59:09.044 INFO [org.waarp.openr66.protocol.utils.ChannelUtils] [main] org.waarp.openr66.protocol.utils.ChannelUtils.exit(ChannelUtils.java:401) : Exit Shutdown Local
11/02/2016/16:59:09.045 DEBUG [org.waarp.openr66.protocol.localhandler.LocalTransaction] [main] org.waarp.openr66.protocol.localhandler.LocalTransaction.closeAll(LocalTransaction.java:475) : close All Local Channels
11/02/2016/16:59:09.059 INFO [org.waarp.openr66.protocol.utils.ChannelUtils] [main] org.waarp.openr66.protocol.utils.ChannelUtils.exit(ChannelUtils.java:405) : Exit Shutdown LocalExec
11/02/2016/16:59:09.060 INFO [org.waarp.openr66.protocol.utils.ChannelUtils] [main] org.waarp.openr66.protocol.utils.ChannelUtils.exit(ChannelUtils.java:409) : Exit Shutdown Command
11/02/2016/16:59:09.061 INFO [org.waarp.openr66.protocol.utils.ChannelUtils] [main] org.waarp.openr66.protocol.utils.ChannelUtils.terminateCommandChannels(ChannelUtils.java:155) : ServerChannelGroup: 0
11/02/2016/16:59:09.064 INFO [org.waarp.openr66.protocol.utils.ChannelUtils] [main] org.waarp.openr66.protocol.utils.ChannelUtils.exit(ChannelUtils.java:411) : Exit Shutdown Db Connection
11/02/2016/16:59:09.064 INFO [org.waarp.openr66.protocol.utils.ChannelUtils] [SubTask-2] org.waarp.openr66.protocol.utils.ChannelUtils$R66ChannelGroupFutureListener.operationComplete(ChannelUtils.java:137) : Start with shutdown external resources for ServerChannelGroup
11/02/2016/16:59:09.065 INFO [org.waarp.openr66.protocol.utils.ChannelUtils] [main] org.waarp.openr66.protocol.utils.ChannelUtils.exit(ChannelUtils.java:413) : Exit Shutdown ServerStop
11/02/2016/16:59:09.100 INFO [org.waarp.openr66.protocol.utils.ChannelUtils] [SubTask-2] org.waarp.openr66.protocol.utils.ChannelUtils$R66ChannelGroupFutureListener.operationComplete(ChannelUtils.java:141) : Done with shutdown ServerChannelGroup
11/02/2016/16:59:09.129 DEBUG [org.waarp.openr66.proxy.network.NetworkTransaction] [main] org.waarp.openr66.proxy.network.NetworkTransaction.closeAll(NetworkTransaction.java:247) : close All Network Channels
11/02/2016/16:59:09.351 DEBUG [org.waarp.openr66.protocol.localhandler.LocalTransaction] [main] org.waarp.openr66.protocol.localhandler.LocalTransaction.closeAll(LocalTransaction.java:475) : close All Local Channels
11/02/2016/16:59:09.353 DEBUG [org.waarp.openr66.proxy.network.NetworkTransaction] [main] org.waarp.openr66.proxy.network.NetworkTransaction.closeAll(NetworkTransaction.java:264) : Last action before exit
Exit end of Shutdown
Exit System
Cannot start Proxy OpenR66 for proxy1R66
</code></pre>
I want to start proxy in a separated host from R66 server on port 6667 in order to forward ssl traffic to proxified server R66 also listening on ssl 6667, so locally on proxy I dont have any port binded...
Currently my proxy-config is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:x0="http://www.w3.org/2001/XMLSchema">
    <comment>Example of config file: change its as your need.</comment>
    <identity>
        <hostid>proxy1R66</hostid>
        <sslhostid>proxy1R66</sslhostid>
        <cryptokey>/opt/R66/certs/test-key.des</cryptokey>
        <authentfile>/opt/R66/conf/OpenR66-authent-A.xml</authentfile>
    </identity>
    <server>
        <serveradmin>admin</serveradmin>
        <noserverpasswd>0554eb160326e7b1893eecb714f52fc6</noserverpasswd>
        <serverpasswdfile>/opt/R66/certs/test-passwd-http.ggp</serverpasswdfile>
        <usenossl>True</usenossl>
        <usessl>True</usessl>
        <usehttpcomp>False</usehttpcomp>
        <uselocalexec>False</uselocalexec>
        <httpadmin>/opt/R66/httpadmin</httpadmin>
        <admkeypath>/opt/R66/certs/testsslnocert.jks</admkeypath>
        <admkeystorepass>testsslnocert</admkeystorepass>
        <admkeypass>testalias</admkeypass>
        <pastlimit>86400000</pastlimit>
        <minimaldelay>5000</minimaldelay>
        <snmpconfig>/opt/R66/conf/snmpconfig-proxy.xml</snmpconfig>
    </server>
    <network>
                <serverproxy>
                        <serverlistenaddr>proxy1R66</serverlistenaddr>
                        <serverlistenport>6667</serverlistenport>
                        <serverlistenssl>true</serverlistenssl>
                        <serverremoteaddr>R66</serverremoteaddr>
                        <serverremoteport>6667</serverremoteport>
                        <serverremotessl>true</serverremotessl>
                </serverproxy>
        <serverhttpport>10086</serverhttpport>
        <serverhttpsport>10087</serverhttpsport>
    </network>
    <ssl>
        <keypath>/opt/R66/certs/testsslnocert.jks</keypath>
        <keystorepass>testsslnocert</keystorepass>
        <keypass>testalias</keypass>
        <trustkeypath>/opt/R66/certs/testcert.jks</trustkeypath>
        <trustkeystorepass>testcert</trustkeystorepass>
        <trustuseclientauthenticate>True</trustuseclientauthenticate>
    </ssl>
    <directory>
        <serverhome>/opt/R66</serverhome>
        <arch>arch</arch>
        <conf>conf</conf>
    </directory>
    <limit>
        <timeoutcon>10000</timeoutcon>
        <serverthread>2</serverthread>
        <clientthread>4</clientthread>
        <memorylimit>4000000000</memorylimit>
        <sessionlimit>0</sessionlimit>
        <globallimit>0</globallimit>
        <delaylimit>10000</delaylimit>
        <usecpulimit>False</usecpulimit>
        <usejdkcpulimit>False</usejdkcpulimit>
        <cpulimit>0.9</cpulimit>
        <connlimit>0</connlimit>
        <lowcpulimit>0.5</lowcpulimit>
        <highcpulimit>0.9</highcpulimit>
        <percentdecrease>0.25</percentdecrease>
        <delaythrottle>1000</delaythrottle>
        <limitlowbandwidth>4096</limitlowbandwidth>
                <checkversion>True</checkversion>
    </limit>
</config>
```

**Comment by fredericBregier** [comment]
I have to debug a bit to find out. Could you try with a different port in serverlistenport since I suspect that default value 6667 is in conflict for a still unknown reason yet ?

**Comment by alexbarta** [comment]
Just changed ```<serverlistenport>16667</serverlistenport>``` , but same error output appears unfortunately

**Comment by fredericBregier** [comment]
Thanks for the confirmation. I continue to investigate...

**Comment by fredericBregier** [comment]
I found it ! Thta's an internal bug. It will be fix in the next release.

**Comment by alexbarta** [comment]
Great news! Thank you! When will be released the new version? If you don't mind, could you please share the new Proxy jar so I can try on my own?  Thank you again for the speedy response.

**Comment by fredericBregier** [comment]
The new version is not fully ready yet but I published a beta2 version on sourceforge, ready to be downloaded (or so, according to the delay of sf to manage the mirrors).
You can check this version. Note you need to upgrade all jar (no need to upgrade the database however).

**Comment by alexbarta** [comment]
Ok cool, I will try the beta2 then.

**Comment by alexbarta** [comment]
I confirm that proxy is now starting...

**Comment by fredericBregier** [comment]
Can I close this issue since you opened a new one?

**Comment by alexbarta** [comment]
Yes please.

**Comment by fredericBregier** [comment]
Thanks
